### ISSUE TITLE
Cannot Open include file: "includes.h": No Such file or directory

### ISSUE THREAD

**Issue by Thman558** [clauadv/dbd_internal#20]
I Am getting this error within 32 different files

**Comment by clauadv** [comment]
build in release

**Comment by Thman558** [comment]
Thank you however it is also missing the minhook files.

**Comment by Ayoub56** [comment]
same error

**Comment by Thman558** [comment]
Stfu you just made a shitty program

**Comment by clauadv** [comment]
> Stfu you just made a shitty program

thats why r u here cuz its shitty :)
